custom:
  allowed:
    file:
      types: image/jpeg,image/png

spring:
  profiles:
    active: local
  datasource:
    username: postgres
    password: postgres_password
    driver-class-name: org.postgresql.Driver
  flyway:
    user: postgres
    password: postgres_password
    locations: classpath:db/migration/main
  data:
    redis:
      reminder:
        dates:
          key: reminderDates
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    s3:
      bucket: present-service-bucket
    region:
      static: us-east-1
    credentials:
      access-key: test
      secret-key: test
    endpoint:
      s3: http://localhost:4566

  localstack:
    s3:
      bucket: present-service-bucket