spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/main

logging:
  level:
    org.flywaydb: TRACE
    root: DEBUG  # Set root logger to DEBUG level to capture all logs
    org.springframework.web: DEBUG  # Set Spring Web logs to DEBUG level for request logging
    org.hibernate.SQL: DEBUG  # Set Hibernate SQL logs to DEBUG level
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Set SQL parameter binding logs to TRACE level

services:
  address:
    user: "http://localhost:8081"