server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/presents
  flyway:
    url: jdbc:postgresql://localhost:5434/presents
  #  data:
  #    mongodb:
  #      host: localhost
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.flywaydb: TRACE
    org.hibernate.SQL: TRACE
    org.apache:
      kafka:
        clients:
          producer:
            internals: TRACE