spring:
  datasource:
    url: jdbc:postgresql://postgres-presents:5432/presents
  flyway:
    url: jdbc:postgresql://postgres-presents:5432/presents
  #  data:
  #    mongodb:
  #      host: mongo
  kafka:
    bootstrap-servers: kafka:9092
  data:
    redis:
      host: redis
      port: 6379

services:
  address:
    user: "http://user-service:8080"