server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/presents
  flyway:
    url: jdbc:postgresql://localhost:5434/presents
  #  data:
  #    mongodb:
  #      host: localhost
  kafka:
    bootstrap-servers: localhost:9092

#logging:
#  level:
#    org.flywaydb: TRACE
#    root: DEBUG  # Set root logger to DEBUG level to capture all logs
#    org.springframework.web: DEBUG  # Set Spring Web logs to DEBUG level for request logging
#    org.hibernate.SQL: DEBUG  # Set Hibernate SQL logs to DEBUG level
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Set