custom:
  environment: local

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/presents
  flyway:
    url: jdbc:postgresql://localhost:5434/presents
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
      port: 6379

services:
  address:
    user: "http://localhost:8081"